spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_gestion_aulas
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # sql:
  #   init:
  #     mode: always
      
  thymeleaf:
    cache: false
