spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_gestion_aulas
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## CON ESTO, SPRING CREA LAS TABLAS SEGUN NUESTRAS ENTITIES. NO USA EL `schema.sql` ni `data.sql`
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     dialect: org.hibernate.dialect.MySQL5Dialect


  # sql:
  #   init:
  #     mode: always
      
  thymeleaf:
    cache: false
